<html><!-- InstanceBegin template="/Templates/index.dwt" codeOutsideHTMLIsLocked="false" -->
<head>
<!-- InstanceBeginEditable name="doctitle" -->
<title>Merideon</title>
<!-- InstanceEndEditable -->
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!-- InstanceBeginEditable name="head" -->
<style type="text/css">
<!--
.style3 {font-size: 16px; color: #666600; font-style: normal; font-family: "Verdana", "Arial", "Helvetica", "sans-serif";}
-->
</style>
<!-- InstanceEndEditable -->
<style type="text/css">
<!--
body {
	background-image:     url(images/background_06.jpg);
	margin-left: 0px;
	margin-top: 10px;
	margin-right: 0px;
	margin-bottom: 10px;
}
-->
</style>
<link href="merideon.css" rel="stylesheet" type="text/css">
</head>

<body>
<table border="0" cellpadding="0" cellspacing="0" align="center" valign="top">
      <tr>
        <td align="center" colspan="3" valign="top"><div style="border-radius: 10px; width: 770px; overflow: hidden;"><iframe src="http://clips.animatron.com/88639f7d44ab1e1bba244595f08cf7f4?w=770&h=222&autoPlay=1" width="770" height="222" frameborder="0"></iframe></div></td>
      </tr>
	  <tr>
		<td width="5%"><img src="images/spacer.gif" /></td>
	    <td align="center" width="90%" bgcolor="#8C6809"><?php include ("nav.php"); ?></td>
		<td width="5%"><img src="images/spacer.gif" /></td>
	  </tr>
      <tr>
        <td colspan="3">
			<div class="bodycorners">
			<div class="hometitle">About Us</div>
			<hr style="background-color: #8C6809; height: 12px;"/>
			<span class="bodysubtitle">Our Mission</span>
			<p align="justify" class="body"> Merideon&trade; believes in the extraordinary value of Traditional Chinese Medicine and its ability to effectively complement modern medical practice. However, the value of an herbal formula is contingent upon its purity, lack of contaminants, and potency of ingredients. Unfortunately, many other herbal products are of questionable efficacy due to poor manufacturing practices or quality control. Merideon&trade; offers only safe and effective herbal products created under detailed manufacturing scrutiny with batch-to-batch consistency. In addition to providing qualified physicians with products of only the finest quality, Merideon&trade; is also the exclusive provider of a powerful, dynamic, and highly efficient modular patent-pending system of herbal formulations derived from Tsun-Nin Lee, M.D, one of the pioneers and leading educators of Traditional Chinese Medicine. Merideon&trade; is foremost dedicated to promoting the ethical and correct use of TCM for the benefit of consumers. </p>
			<span class="bodysubtitle">Our Philosophy</span>
			<p align="justify" class="body">On all Merideon&trade; product labels and on this website, you will find our unique logo design. The images depicted are very symbolic and reflect the pillars of Traditional Chinese Medicine (TCM) as well as the guiding philosophies of Merideon&trade;. </p>
            <p align="justify" class="body">Balance of the Five Elements, Earth, Metal, Water, Wood, and Fire is a core concept for TCM. Each Element is represented on the logo with the mountain representing Earth, rocks representing Metal (since metal is found in rock), a river representing Water, bamboo representing Wood, and the Kirin (a mythical fire-based creature) representing Fire. </p>
            <p align="justify" class="body">The Kirin is also a legendary creature representing good fortune, virtue, and justice. Accordingly, Merideon&trade; strives to provide only the best quality herbal products for their ethical and judicious use through trained physicians. The direction the Kirin is facing, from east to west, symbolizes Merideon's intent to help further integrate Traditional Chinese Medicine with modern Western medicine. </p>
			</div></td>
		</div>
		</td>
      </tr>
    </table>

<script type="text/javascript" src="js/ieupdate.js"></script>


</body>
<!-- InstanceEnd --></html>
<!-- text below generated by server. PLEASE REMOVE --><!-- Counter/Statistics data collection code --><script language="JavaScript" src="http://l.yimg.com/d/lib/smb/js/hosting/cp/js_source/whv2_001.js"></script><script language="javascript">geovisit();</script><noscript><img src="http://visit.webhosting.yahoo.com/visit.gif?us1444496233" alt="setstats" border="0" width="1" height="1"></noscript>