apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: merideon
spec:
  selector:
    matchLabels:
      app: nginx-php-fpm
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-php-fpm
    spec:
      containers:
      - name: nginx-php-fpm
        image: richarvey/nginx-php-fpm
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-php-fpm-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx-php-fpm-service
